// Centralized re-exports of Phosphor icons to keep imports consistent across the app.
// Uses the main (CSR) bundle to ensure all symbols are present; Activity maps to ActivityIcon.
export {
  ActivityIcon as Activity,
  Archive,
  ArrowClockwise,
  ArrowRight,
  ArrowsLeftRight,
  BatteryCharging,
  BatteryChargingVertical,
  BatteryWarning,
  BatteryWarningVertical,
  Bell,
  BellSlash,
  BookOpen,
  CheckCircle,
  ChartLine,
  Circle,
  Database,
  Download,
  Eye,
  EyeSlash,
  FastForward,
  FileArrowDown,
  FileText,
  Funnel,
  Flask,
  FolderOpen,
  Gear,
  IdentificationCard,
  Keyboard,
  Lightbulb,
  LockSimple,
  MagnifyingGlass,
  MapPin,
  Pause,
  Play,
  Plus,
  Question,
  Rewind,
  ShieldCheck,
  ShieldWarning,
  SkipBack,
  SkipForward,
  Sliders,
  Sparkle,
  Stop,
  Trash,
  Upload,
  Warning,
  WifiHigh,
  WifiSlash,
  Wrench,
  XCircle,
} from '@phosphor-icons/react'
